### ISSUE TITLE
Master Ticket: Oblique Quest Issues

### ISSUE THREAD

**Issue by Vohras2** [NebulaMC-GG/Bugs-and-Issues#1113]
Repository for confirmed Quest related issues for Oblique.

https://github.com/ObliqueNET/Server/issues/1067 - Triggers attached to a log-off objective do not activate when a player logs off.

https://github.com/ObliqueNET/Server/issues/1042 - Give command not working with quests after previously doing so.

https://github.com/ObliqueNET/Server/issues/956 - Using the /endbattle command does complete Battle_End_Abnormal. However any other way that should complete the objective does not work, or is not completing the whole set of triggers. These include logging off, /kick command, closing MineCraft, and Alt+F4.

https://github.com/ObliqueNET/Server/issues/847 - The has_completed condition currently does not detect the completion of individual objectives that are part of a stage that has been marked complete. This does work for checking objectives of the same stage that is not complete, as it currently works for "Life and Destruction".

https://github.com/ObliqueNET/Server/issues/1175 - Reset command for all player quests has stopped working.

///// Requests \\\\\
https://github.com/ObliqueNET/Server/issues/991 - Entry Zones to disable flying.

https://github.com/ObliqueNET/Server/issues/1041 - Weather set at start of battle.

**Comment by KittyKatzyn** [comment]
Closing as the quest system is being/has been completely overhauled for 1.16.5.
