### ISSUE TITLE
Latias Flying 2 Fast

### ISSUE THREAD

**Issue by KoreanNino** [NebulaMC-GG/Bugs-and-Issues#1409]
When the Latias spawned yesterday flew away too fast and I had a problem catching the Latias. Since it flew away too fast where the pokemon despawned. Sadly don't have any evidence of the Latias. However, I know no one caught it on the server. :(

**Comment by Khrisstias** [comment]
Can confirm a Latias spawned yesterday. All flying spawns are incredibly fast and are hard to catch up to unless you have /fly. I have lost a shiny wingull to this, and two rayquazas have also despawned from flying away too fast.

**Comment by MissElyri** [comment]
Who did the Rayquazas spawn on? @Khrisstias

**Comment by Khrisstias** [comment]
> Who did the Rayquazas spawn on? @Khrisstias

One if them i know was Shika, the other i have no clue

**Comment by KittyKatzyn** [comment]
Going through old tickets!

This issue has been forwarded to the Pixelmon Internal tracker. :)
