### ISSUE TITLE
Thunderstone spawning?

### ISSUE THREAD

**Issue by RudolfShmitler** [NebulaMC-GG/Bugs-and-Issues#1411]
Thunderstone ore appears to have been replaced by moonstone ore in the wilderness. The pixelmon wiki lists thunderstone ore as spawning in stone at 74 or higher, and moonstone ore with no spawn locations. Moonstone ore is very easy to find in those conditions, with no thunderstone ore in sight.

**Comment by KittyKatzyn** [comment]
Pixelmon has changed the spawning method for Thunder stone ore (and updated the wiki to reflect this) - it now only spawns when lightning strikes stone.

Closing!
