### ISSUE TITLE
GD Town Chat Shows Messages in Gen Chat

### ISSUE THREAD

**Issue by ProfAwesome100** [NebulaMC-GG/Bugs-and-Issues#1414]
Basically what the title says,

Town Claim is made, people are trusted, and even gives the "Town Chat Enabled" after running the command, but when we talk it shows up in general chat. 

Are we doing something wrong? I don't even know how GD would account for town chat anyways since you can technically be a part of multiple town chats since multiple ppl can make a town claim. So is there a way to formally invite people besides trusting them like chat says?

Any help would be cool!
(ps. I've only tried this on Atlas so idk if its exclusive to atlas or everyone)
Thanks,
Prof

**Comment by Rasgnarok** [comment]
That's a good question, I'll need to test and see if it's one of our plugins wrongly parsing town chat.
