### ISSUE TITLE
Tags not showing in Hub

### ISSUE THREAD

**Issue by Chunkkss** [NebulaMC-GG/Bugs-and-Issues#1415]
![2022-06-12_21 37 03](https://user-images.githubusercontent.com/107234416/173275119-ae1adb44-28f5-4707-b337-e00b4712ffdc.png)

![2022-06-12_21 37 15](https://user-images.githubusercontent.com/107234416/173275129-fe73a4b5-c3e9-4392-9e8b-3a08a1158c6e.png)

Equipped Parkour tag, not showing in chat even when equipped.

**Comment by CenizaRey** [comment]
We are in the process of removing tags from the hub. Thanks for the report! Closing
