### ISSUE TITLE
Mounting pokemons or claiming pokeball loots while in claims

### ISSUE THREAD

**Issue by Lieren-HuntGhosts** [NebulaMC-GG/Bugs-and-Issues#1443]
It is impossible to claim pokeball loots or to mount your pokemon when in other people's claims. This is basically a reminder for Ras to check that :P

**Comment by Chunkkss** [comment]
Claimflags can adjust that, it's known in rules to not claim pokeloots. Claimflags can be adjusted to let trusted or non-trusted players mount their mons as well.
