### ISSUE TITLE
Shulker dupe with /mirror

### ISSUE THREAD

**Issue by PenginKami** [NebulaMC-GG/Bugs-and-Issues#1470]
Doesn't dupe the contents thankfully, and doesn't destroy contents either.
You need /mirror active
exactly 2 (No more, no less) shulker boxes in your inventory with items within each.
![2022-06-19_19 47 24](https://user-images.githubusercontent.com/96862959/174475600-7484c1ed-c251-4457-a1af-858dc26524f8.png)
![2022-06-19_19 47 28](https://user-images.githubusercontent.com/96862959/174475602-fde89318-09be-49a7-b7fd-cb0bf46d0cc2.png)
![2022-06-19_19 47 38](https://user-images.githubusercontent.com/96862959/174475604-98ba693b-6196-41c4-a589-ff7c6b783d7f.png)

Don't disable /mirror as I made this Lapras using it ❤️ 
![2022-06-19_19 46 36](https://user-images.githubusercontent.com/96862959/174475553-e4a171fd-ff2a-45ba-ac08-1d5e936f853f.png)

**Comment by KittyKatzyn** [comment]
Forwarded to the Internal tracker!  Will update here when fixed!

**Comment by chefburne** [comment]
No longer an issue. Thanks for reporting, closing!
