### ISSUE TITLE
Broken Textures

### ISSUE THREAD

**Issue by Zoru-chan** [NebulaMC-GG/Bugs-and-Issues#1496]
![Strike](https://user-images.githubusercontent.com/77426379/175034277-94cd22d3-ed58-4892-b0a9-a9fb58ec7a34.png)

miguipkv on Atlas server found a strike textured golbat and it is broken. Also the ancient heavy balls (for sure) are broken textures for the icon around pokemon in your party.

**Comment by HackuJacku** [comment]
Just confirmed that the Strike-palette is now fixed
