### ISSUE TITLE
Problem with riding pokemon

### ISSUE THREAD

**Issue by redx10** [NebulaMC-GG/Bugs-and-Issues#1497]
Hi, theres a pretty big issue with riding pokemon right now. If your pokemon is on the other side of the world barrier, and you ride it, it will take you through the barrier. Hope this can be fixed easily!

If you have more questions my IGN is Valirus, and my discord is Vali is Invalid #4334

**Comment by Chunkkss** [comment]
Due to glitch. Blocks cannot be touched on the other side of the world border, not as easy to perform this anymore.
