### ISSUE TITLE
Hexcodes not working

### ISSUE THREAD

**Issue by Vavalur** [NebulaMC-GG/Bugs-and-Issues#1549]
When using hex codes you can only use combinations of FF and 00. any other hex code will return a white nickname. Regular Minecraft color codes (&#) work as expected.

Returns White:
#47bdbd #5dc5a5 #73cd8e #89d576 #9fdd5f #b5e547 #cbed30
#db9157 #c98160 #b87169 #a66272 #95527a #834284 #72338d
#F0000F #F00FFF #FF000F #F0F0F0

Returns Color:
#FF00FF #FF0000 #000000 #FFFFFF #00FFFF #0000FF #00FF00 #FFFF00

Potentially missing perms:
cmi.colors.publicmessage.*
cmi.colors.privatemessage.*
cmi.colors.nickname.*
cmi.colors.signs.*
cmi.colors.books.*
cmi.colors.me.*

**Comment by Vavalur** [comment]
Hex Codes do work properly in /itemname and /itemlore

**Comment by HackuJacku** [comment]
What are you using these hex codes for? Depending on the answer to that question, you are properly using the incorrect format.

**Comment by Vavalur** [comment]
I was trying to use them for /nick and they are in this format {#47bdbd}Text

That format worked for itemname/itemlore, but not nick, chat, signs, or books. Which is odd since it's the same plugin afaik so you'd think the format would be universal.

**Comment by HackuJacku** [comment]
@Vavalur which server is this on please? Using the format {#47bdbd} worked for me

**Comment by Vavalur** [comment]
This is on Titan

**Comment by Vavalur** [comment]
Just tried again today
![Screenshot_23](https://user-images.githubusercontent.com/107285589/184984170-1f0856bd-086d-4f2f-9b18-e0784af615e0.png)
![Screenshot_22](https://user-images.githubusercontent.com/107285589/184984183-4162be97-5469-4de4-8ae6-d4f38a279750.png)

Expected:
![Screenshot_24](https://user-images.githubusercontent.com/107285589/184984204-95c3fd9b-4c75-4134-be0f-32bf7514c0ee.png)

**Comment by HackuJacku** [comment]
What about now please?

**Comment by Vavalur** [comment]
Hexcodes no change
![image](https://user-images.githubusercontent.com/107285589/185152501-89ea5d3f-fd68-4230-8060-29b514e07d3c.png)

&m no strike through name
![image](https://user-images.githubusercontent.com/107285589/185152703-bd344261-a046-4e64-a9ca-d005ccae6739.png)

**Comment by Chunkkss** [comment]
The color codes have been updated / fixed! They should work as intended.
