### ISSUE TITLE
Shrines holograms

### ISSUE THREAD

**Issue by Vavalur** [NebulaMC-GG/Bugs-and-Issues#1550]
Server: Titan
All shrines have &o formatter in their holograms.
![image](https://user-images.githubusercontent.com/107285589/176551227-90b5ed79-c7f1-4803-9b4c-42022e16b3d4.png)

Some shrines like all 3 birds and time space trio have double holograms.
![image](https://user-images.githubusercontent.com/107285589/176551350-60b580c4-3440-428c-ae73-4c2b5696b1d1.png)

**Comment by Menno165** [comment]
This issue also occurs in on Atlas and Orion.

**Comment by HackuJacku** [comment]
These have now been removed, thank you for reporting this :)
