### ISSUE TITLE
Repeat moves choice

### ISSUE THREAD

**Issue by FoxArcher** [NebulaMC-GG/Bugs-and-Issues#1562]
When entering a battle with talonflame TonyStormEagle and uses dynamax after he selects the move it makes him re-enter the attack he wants to do another time. I have also had this happen with my Salamance. I encounter a Pokemon, I select a move and have to reselect after the move ui disappears and reappears.

**Comment by Rasgnarok** [comment]
This should be fixed as of the latest version, but I need this re-confirmed then forwarded to https://pixelmonmod.com/tracker.php?p=2 since this is a Pixelmon bug after all.

**Comment by fatyg5** [comment]
Closing, as assuming fixed due to 5 months of inactivity and no reports to the Pixelmon forums.
