### ISSUE TITLE
General Shop issues/commands

### ISSUE THREAD

**Issue by Chunkkss** [NebulaMC-GG/Bugs-and-Issues#1567]
[ARIA]
missing blue text for the command
![Aria Rank blue text](https://user-images.githubusercontent.com/107234416/177007914-bea12d54-537c-4e63-9070-17154821090a.JPG)

[NOVA]
No /ender permission
![no permission for ender chest](https://user-images.githubusercontent.com/107234416/177007705-457bf5ae-48f9-4a1e-b6b2-f969ca7c8cd5.JPG)
Command doesn't exist in game
![nova command not working in game](https://user-images.githubusercontent.com/107234416/177007708-0ef7eba1-3757-4eaa-8f83-d77aa0e6a153.JPG)
Goofy sounding sentence 
![nova spelling error](https://user-images.githubusercontent.com/107234416/177007715-9d07f289-9a2a-438a-a1a3-8dc3d4c3ec98.JPG)

[JADE]
Command doesn't exist
![jade cosmetic command doesnt exist](https://user-images.githubusercontent.com/107234416/177007646-f0c28e35-484e-45d0-8612-c2d867c224d8.JPG)
/ender is not working
![jade ender not working](https://user-images.githubusercontent.com/107234416/177007658-33341f42-3654-4a4b-acca-9e312ab20d28.JPG)
Hidden power isn't showing on pokemon
![jade not showing hidden power](https://user-images.githubusercontent.com/107234416/177007667-ab4140da-5e5a-49ed-a795-3e6e3341a89f.JPG)
/pokecolor command isn't working
![jade rank pokecolor not working](https://user-images.githubusercontent.com/107234416/177007671-6f986a64-b27b-44f9-968c-6a22a59e3d5d.JPG)
General spelling error, (should be advances)
![jade spelling error](https://user-images.githubusercontent.com/107234416/177007682-1b7400a9-fa3a-401f-93ab-656bcc3e7c35.JPG)

[RUNE]
General spelling error 
![rune spelling error](https://user-images.githubusercontent.com/107234416/177007752-7341dee9-1aa1-4fd3-9762-603de33a75ef.JPG)

[OMEN]
Another general spelling error
![omen spelling error](https://user-images.githubusercontent.com/107234416/177007761-14215294-1edc-46f7-b50f-9e0ca86dd9fe.JPG)

[ARIA -> NOVA UPGRADE]
Half of the text goes from grey to black
![aria to nova upgrade half text grey half text black](https://user-images.githubusercontent.com/107234416/177007769-6fd62270-dc29-476f-9c1a-91c4a4dadcd5.JPG)

[GENERAL SUGGESTION]
Remove the word "access" before every command, just easier on the eyes to read and still reads the same without.
![ALL ranks should have access removed](https://user-images.githubusercontent.com/107234416/177007775-c455c3ca-fa7e-4bc7-9cb2-2e8bf80b3227.JPG)

[CRATES]
non-existent command
![crates keys command non-existant](https://user-images.githubusercontent.com/107234416/177008345-3ea49762-ac56-43d1-8d86-e6519763f670.JPG)

[SOLAR]
Not a reward in solar crate
![not in solar crate](https://user-images.githubusercontent.com/107234416/177008299-cbba6c74-9c28-44c2-b3e0-6043e9e32769.JPG)
![solar crate key rewards dont exist](https://user-images.githubusercontent.com/107234416/177008311-78663501-154c-4e9e-a76c-756935d5e0c4.JPG)
![solar crate rewards dont exist](https://user-images.githubusercontent.com/107234416/177008312-a69b5ca6-97e5-42aa-a536-df7e28b57272.JPG)
![these exist as separate rewards not group](https://user-images.githubusercontent.com/107234416/177008313-644b5856-6e0e-4ac4-880c-bb5fbb427ea4.JPG) (this exists as separate rewards, not group)

[COSMIC]
these rewards dont exist in cosmic crates
![not in cosmic  crate](https://user-images.githubusercontent.com/107234416/177008329-59a62e45-80a9-4da0-bb9e-a404737f1e15.JPG)
![not in cosmic crate](https://user-images.githubusercontent.com/107234416/177008333-5d80c21f-1de6-4e61-bf17-77237e4e9059.JPG)
EXP Candies are L in crate, not XL
![candies are L not XL in crate](https://user-images.githubusercontent.com/107234416/177008385-665bdbc7-185c-4d71-9f77-98545c4b7067.JPG)

[ASTRAL]
These rewards are separate, not grouped
![astral separate rewards](https://user-images.githubusercontent.com/107234416/177008351-92bc4e75-c559-40aa-ab83-f672043cfd49.JPG)
![astral separate rewards2](https://user-images.githubusercontent.com/107234416/177008353-d32da031-05b0-4db0-828c-9f97f5cf84fd.JPG)

Not in astral crates
![not in astral crate 2](https://user-images.githubusercontent.com/107234416/177008374-819da5de-7e64-4411-9c53-9435b3cf71ab.JPG)
![not in astral crate](https://user-images.githubusercontent.com/107234416/177008376-9c78322f-5f41-4fcf-84c8-5b41bd9071f5.JPG)

**Comment by Rasgnarok** [comment]
Some of these had been fixed back in August/July, but seems like there's a few edits (namely formatting) that did not get done. Fixed!
