### ISSUE TITLE
Broken reward?

### ISSUE THREAD

**Issue by Jayparalysis** [NebulaMC-GG/Bugs-and-Issues#1570]
Bought 5 cosmetic keys on Orion and one of the rewards was suppose to be "Stary" but I was given a black trainer hat? Chat said it was a -5 level down. Not sure whats going on.
![Screenshot_1](https://user-images.githubusercontent.com/107003183/177020619-b866a948-6bd6-4a64-8f45-8608edfd834e.png)
Server: Orion
Crate: Cosmetic
Username: CrystalKing
Thank you for your time!

**Comment by HackuJacku** [comment]
Fixed in the crates update :)
