### ISSUE TITLE
unable to buy/sell/trade claimblocks between players

### ISSUE THREAD

**Issue by TonyStormEagle** [NebulaMC-GG/Bugs-and-Issues#1584]
im not sure what are the correct commands to do so, as its not clear, but /sellclaimblocks  says selling and buying is disabled, /transferclaimblocks says it only counts with bonus and attained blocks, not original ones, but even with said blocks you're not allowed to give any away.

**Comment by HackuJacku** [comment]
After looking into this, `/tranferclaimblocks` is now fixed to work with our system. We haven't implimented `/sellclaimblocks` but I will bring it up internally to discuss. Thank you :)
