### ISSUE TITLE
No perms to /marry divorce

### ISSUE THREAD

**Issue by lolanonymous** [NebulaMC-GG/Bugs-and-Issues#1622]
You can marry someone, but you don't have the permission to divorce them

**Comment by fatyg5** [comment]
Marriage is eternal, how dare you!

On a serious note, I don't even know how y'all can use /marry, you don't have the perms. Gonna try to fix.

**Comment by fatyg5** [comment]
Did not fix, will leave open till later

**Comment by Deathnight7976** [comment]
Perms to `/marry divorce` are active on all three servers, solved, closing.
