### ISSUE TITLE
Omen mirror and durability warning not working

### ISSUE THREAD

**Issue by Vavalur** [NebulaMC-GG/Bugs-and-Issues#1635]
/mirror and the durability warning when tools get low are not working
durability warning just never pops up
/mirror no perms
![image](https://user-images.githubusercontent.com/107285589/178503095-6208e9a3-d9e3-4464-baf0-e191580b9906.png)

These were working fine yesterday

**Comment by fatyg5** [comment]
Mirror was removed from Omen due to a bug that we have to find a fix for. I'll have to look into the durability thing.

**Comment by Menno165** [comment]
For the durability:

I tested all minecraft shovels and some pixelmon shovels + a netherite- and thunderstone pickaxe on the beta server.
Results were the following:

minecraft shovels + the netherite pickaxe received a warning on the beta server.
pixelmon shovels + thunderstone pickaxe did not receive a warning on the beta server.

**Comment by fatyg5** [comment]
Mirror may be readded soon if we can get and test the latest CMI update. The durability issue with Pixelmon shovels seems to be an issue within CMI, as it does not look like we can add modded items to it's durability list. Closing due to both of these.
