### ISSUE TITLE
Claim error message shows up in chat for everyone to see

### ISSUE THREAD

**Issue by rthomps6666** [NebulaMC-GG/Bugs-and-Issues#1647]
When a player tries to claim an area that is smaller than 16x16 blocks, an error message pops up in chat for everyone to see.

See the screenshot below.

![image](https://user-images.githubusercontent.com/103296027/179044082-03691c72-a70a-4466-83cc-fcce27ef9230.png)

**Comment by KittyKatzyn** [comment]
Hi there!

I'm currently going through older tickets, and upon testing this issue, I can see that since we recently decreased the minimum size a claim can be, you can no longer proc this issue! Yay!

Thanks!
