### ISSUE TITLE
Random Hidden Ability Pokemon Issue / Support [Cosmic Crate]

### ISSUE THREAD

**Issue by oliverze1** [NebulaMC-GG/Bugs-and-Issues#1655]
When I bought a cosmic crate, I got one random Pokémon with a hidden ability. This Pokémon was Cryogonal which is a Pokémon that only has one ability "Levitate" making it that I got a Pokémon with no "hidden ability" and only a Pokémon that's semi-common. There should be a fix to Cosmic crates random hidden ability Pokémon making it so the random hidden ability Pokémon you get from cosmic crates actually have a hidden ability.

![HA proof](https://user-images.githubusercontent.com/108959844/179372690-870ee892-36fd-498a-a90c-989aa9273f2b.PNG)
![levitate](https://user-images.githubusercontent.com/108959844/179372693-8f52ebaf-e321-43c0-a08e-586245d8e0d6.PNG)
![unbreedable](https://user-images.githubusercontent.com/108959844/179372682-4681f7a0-30e9-4e39-9e62-9444924eaa98.PNG)

**Comment by CaptainTCovenant** [comment]
Adding on to this: 

Server: Orion
Cosmic crate fails to generate HA pokes regardless of having one ability. 
Here I pulled a Grovyle from the crate at some point around 6/17/22, but it was Overgrow. 
![Screenshot_162](https://user-images.githubusercontent.com/92965754/179373363-83a4c51f-b834-443b-ab71-763bbcc7f65f.png)

![Screenshot_163](https://user-images.githubusercontent.com/92965754/179373365-a5f7a0e5-5779-40b6-b042-d0b8022c7bcc.png)

**Comment by HackuJacku** [comment]
This issue was resolved by a PixelmonMod update, it is now fixed. @MissElyri will handle a refund :)

**Comment by HackuJacku** [comment]
Closing as resolve :)
