### ISSUE TITLE
Transfer Tutor Broken | No Move Tutor

### ISSUE THREAD

**Issue by oliverze1** [NebulaMC-GG/Bugs-and-Issues#1665]
The transfer tutor simply doesn't work and there's no move tutor, though I have heard that the move tutor may come with the adventure map, but for now it leaves many moves unobtainable. The transfer tutor still needs a rework/fix currently though as it says no matter what/where I try to put the items it wants it says I don't have the proper items after I select the move I want to transfer to my Pokémon.

**Comment by xWattzz** [comment]
Bumpppp! please fix 2 issues open with this

**Comment by Chunkkss** [comment]
This issue has been solved. The transfer tutor is working as intended. Looking into getting move tutor placed.
