### ISSUE TITLE
Notes don't sync between servers

### ISSUE THREAD

**Issue by itanomaly** [NebulaMC-GG/Bugs-and-Issues#1669]
Player notes do not sync between players, I can have notes in Orion for example and they won't show in Titan/Atlas.

**Comment by KittyKatzyn** [comment]
Still an issue; will be migrated to Internal.

**Comment by KittyKatzyn** [comment]
Forwarded to the Internal tracker!  Will update here when fixed!

**Comment by chefburne** [comment]
no longer an issue, closing
