### ISSUE TITLE
Raid den did not trigger /hunts rewards

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Bugs-and-Issues#1680]
After completing and catching a Toucannon raid /hunts did not reward me despite the mon qualifying all requirements.

/hunts : 
![toucan](https://user-images.githubusercontent.com/17133410/180920808-43d7f263-a153-4da4-a549-75b1a69f3e3e.png)

IVS:
![toucan2](https://user-images.githubusercontent.com/17133410/180920852-8e22d0d0-062f-4d82-835b-9d97f15ba92f.png)

Growth:
![toucan3](https://user-images.githubusercontent.com/17133410/180920882-1c174f9c-bcab-4534-a6c5-2f5dfe5ebc68.png)

**Comment by MissElyri** [comment]
The gender also has to be female. Is it?

**Comment by Deathnight7976** [comment]
Gender:
![toucan4](https://user-images.githubusercontent.com/17133410/180922100-c10db5f9-a438-4b6d-a6ff-07cbb1e080e2.png)

**Comment by HackuJacku** [comment]
Hello! I have confirmed in the plugin that raid captures do count towards active hunts. 

Can you re-test this for me please, @Deathnight7976, and let me know your results please? I will do the same :)

**Comment by Deathnight7976** [comment]
Will do once I get back from Vaca tmrw

**Comment by HackuJacku** [comment]
> Will do once I get back from Vaca tmrw

Sounds good. It's been a couple of days, are there any updates please?

**Comment by Deathnight7976** [comment]
I have not encountered a raid den that has been on hunts as of yet, there not that common but ill keep you updated when i do.

**Comment by Deathnight7976** [comment]
Still broken:
![ducklet1](https://user-images.githubusercontent.com/17133410/184260544-a6f3aec1-9d51-43fe-b6c0-d8d8e9490fa9.png)
![ducket2](https://user-images.githubusercontent.com/17133410/184260548-8594dc0d-42a0-4c13-971d-23820626e9d1.png)

**Comment by KittyKatzyn** [comment]
Having done a few of these tests now, I feel confident saying this should no longer be an issue.  Closing!
