### ISSUE TITLE
/claimbuy - claim TP enabled

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Bugs-and-Issues#1685]
Everyone can teleport to claims yet again by listing it on /claimbuy and then clicking the [TP] button.
![Claimtp](https://user-images.githubusercontent.com/17133410/181135393-74eb5c23-d608-4844-818f-fa7dcd8ffa17.png)

**Comment by manlybro2002** [comment]
lol shame i cant tp to em

**Comment by KittyKatzyn** [comment]
Still an issue! Needs to be mirgated!

**Comment by KittyKatzyn** [comment]
Forwarded to the Internal tracker!  Will update here when fixed!

**Comment by ElementalMP** [comment]
Resolved, permissions updated.
