### ISSUE TITLE
Sinistea Wiki : biome not working

### ISSUE THREAD

**Issue by FoxArcher** [NebulaMC-GG/Bugs-and-Issues#1705]
![image](https://user-images.githubusercontent.com/108157492/182910386-7e948d23-227e-4702-9d9e-ac047ca2dcc7.png)

**Comment by Rasgnarok** [comment]
Command needs to be entirely rewritten, this plugin is mad jank

**Comment by KittyKatzyn** [comment]
Closing, as we no longer use this plugin!
