### ISSUE TITLE
Crates Megathread

### ISSUE THREAD

**Issue by Rasgnarok** [NebulaMC-GG/Bugs-and-Issues#1709]
https://github.com/NebulaMC-GG/Support/issues/1570

**Comment by Rasgnarok** [comment]
https://github.com/NebulaMC-GG/Support/issues/1673

**Comment by Rasgnarok** [comment]
refunding: https://github.com/NebulaMC-GG/Support/issues/1655

**Comment by Rasgnarok** [comment]
https://github.com/NebulaMC-GG/Support/issues/1639

**Comment by Rasgnarok** [comment]
https://github.com/NebulaMC-GG/Support/issues/1569

**Comment by HackuJacku** [comment]
New crates update is now live :)
