### ISSUE TITLE
Transfer Tutor is broken

### ISSUE THREAD

**Issue by EzelBerbier** [NebulaMC-GG/Bugs-and-Issues#1715]
For some reason the Transfer Tutor on spawn is broken and doesn't let u learn the moves having the necessary items he requested to learn the move. I tried it with different moves and materials and nothing. 

I don't know if the issue only happen on Atlas or is common in the other servers.

**Comment by xWattzz** [comment]
Bumpppp! Happens on Titan also unusable

**Comment by Chunkkss** [comment]
Working as intended. Thanks for the report!
