### ISSUE TITLE
Didn't Receive mon

### ISSUE THREAD

**Issue by DarkSayian** [NebulaMC-GG/Bugs-and-Issues#1733]
So a legendary spawned on a guy a heatran to be exact in the nether. I tped to him i told him you want it? he didnt answer and left i waited like 10 minutes for his response nothing he left nether so i caught it and i dont have it neither in my 6s or my pc idk why i used a master ball on it i have screenys showing that i caught it.

**Comment by MissElyri** [comment]
Could you send me a screenshot either here, or in my DMs on discord? Elyri#2065 and we'll get this sorted for you

**Comment by HackuJacku** [comment]
Closing as no response
