### ISSUE TITLE
/wiki egggroup broken

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Bugs-and-Issues#1734]
/wiki mon egggroup returns this:
![egggroup](https://user-images.githubusercontent.com/17133410/184487135-b27eceb7-47fd-4ecc-a984-8562e789c177.png)

**Comment by HackuJacku** [comment]
The `/wiki` command is being overhauled and replaced when we update to Pixelmojn 9.0.9. Consequently, I will be closing this ticket due to this and as the developer hasn't resolved this issue.
