### ISSUE TITLE
Move "Infernal Parade" on wrong Pokemon

### ISSUE THREAD

**Issue by Liam9950** [NebulaMC-GG/Bugs-and-Issues#1739]
Some Pokemon seem to have infernal parade. Ive seen both a Manaphy and my Kleavor with it, which of course should not be able to learn it.

**Comment by CenizaRey** [comment]
I can't seem to get this to reproduce. How exactly did you get your pokemon to learn this move?

**Comment by Liam9950** [comment]
I recieved the kleavor through trade with AshOfTheCosmos and it already had it.

**Comment by CenizaRey** [comment]
Fixed, closing
