### ISSUE TITLE
Pressing the sort button with XP all makes you crash

### ISSUE THREAD

**Issue by dvos1998** [NebulaMC-GG/Bugs-and-Issues#1743]
Sometimes when you press the sort button in your inventory with an XP all it crashes the game. I attached the log from when it crashed

[CrashReportXPallBug.txt](https://github.com/NebulaMC-GG/Support/files/9351796/CrashReportXPallBug.txt)

**Comment by HackuJacku** [comment]
@Rasgnarok @Khrisstias - potentially an incompatibility with JEI, can this be tested please?

**Comment by Khrisstias** [comment]
Hello! Thanks for the report! I sadly (or well, thankfully) have not been able to replicate this bug with your version of invtweaks. Even made sure I had the exact version of the rest of your mods as well minus pixelmon.
