### ISSUE TITLE
Beast kit - Orion

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Bugs-and-Issues#1744]
I redeemed my weekly Beast kit on Orion and only got 10x L Exp Candies.
The weekly beast kit is missing:
3x Golden Hour Glasses
1x Colorful Shake
16x Dusk Balls
16x Ultra balls

Server: Orion
IGN: Deathnight7976

**Comment by MissElyri** [comment]
Sorry for the *extremely* late reply; Was this ever refunded? If not, let me know and I will get that sorted out for you.

**Comment by Deathnight7976** [comment]
Was not.

**Comment by HackuJacku** [comment]
Sorry for the delay but I have now refunded you :)
