### ISSUE TITLE
/chatcolors applying to the wrong chat

### ISSUE THREAD

**Issue by CaptainTCovenant** [NebulaMC-GG/Bugs-and-Issues#1747]
/chatcolor applies the color to staffchat and not public chat. 
![Screenshot_242](https://user-images.githubusercontent.com/92965754/185266354-326df52f-b5b1-4dc0-914c-41c607a3145c.png)
![Screenshot_243](https://user-images.githubusercontent.com/92965754/185266355-3602dafb-7e03-4876-978b-bd96c0afa31e.png)

**Comment by HackuJacku** [comment]
Fixed, thank you for reporting this :)
