### ISSUE TITLE
Pokedollars from bingo are not rounded

### ISSUE THREAD

**Issue by Gealt** [NebulaMC-GG/Bugs-and-Issues#1748]
Today I got 2499.XXXXXXXXXX75 or so dollars from completing a row and 7499.XXXXXXXXXXXXXXX95 for completing the bingo

I'll add screenshots tomorrow with the new bingo.

**Comment by Gealt** [comment]
![image](https://user-images.githubusercontent.com/41056861/185674704-0b45c11e-c97c-452a-93c0-9e8d18a96d50.png)

**Comment by KittyKatzyn** [comment]
As far as I can tell, these have been fixed!  :)
