### ISSUE TITLE
Omen weekly kit missing items (Atlas)

### ISSUE THREAD

**Issue by lolanonymous** [NebulaMC-GG/Bugs-and-Issues#1750]
![image](https://user-images.githubusercontent.com/39723405/185538249-39dfd91a-522c-40c7-b803-aff0adc55f02.png)
![image](https://user-images.githubusercontent.com/39723405/185538270-31c74775-c8b3-42c9-af3d-70f60b9a37b9.png)

Omen weekly kit is missing XL exp candies, super repel, golden lenses, and golden hourglasses.

**Comment by lolanonymous** [comment]
also mod note refunded

**Comment by fatyg5** [comment]
Fixed, thanks for the report.
