### ISSUE TITLE
Eevee texture 

### ISSUE THREAD

**Issue by Quadehar97** [NebulaMC-GG/Bugs-and-Issues#1751]
Server atlas 
Ign: Quadehar97 

The other day I caught a eevee with the creator texture (team rocket outfit) but on the server it shows up as broken with purple and black squares. Just tested it in single player to make sure its not a mod issue and it works there (Sorry bad pics but best I can do)
![20220819_134858](https://user-images.githubusercontent.com/67765177/185671451-f1242158-5fb7-48d0-9b6f-378f4b7fb3e3.jpg)
![20220819_134846](https://user-images.githubusercontent.com/67765177/185671459-ac9e4c01-9eb4-4bbf-8a7e-93f1d8572e26.jpg)

**Comment by Quadehar97** [comment]
Just wondering if this has been looked at since

**Comment by KittyKatzyn** [comment]
Hi there!  Thanks for your report!

An error has been fixed with the texture/model in our datapack for the next version :)
