### ISSUE TITLE
Legend Pokemon Dexing - Orion

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Bugs-and-Issues#1756]
Regidrago dex's via trade. 
I received a Regidrago via wondertrade and it dexed.

Screenies:
![Regidrago](https://user-images.githubusercontent.com/17133410/185753584-e7776be9-685d-4fed-a052-4ea4efe58235.png)
![Dex](https://user-images.githubusercontent.com/17133410/185753727-5999fea7-4989-44bb-8081-18ce296608f1.png)

**Comment by KittyKatzyn** [comment]
Still an issue!  Needs to be migrated to Internal!

**Comment by KittyKatzyn** [comment]
Forwarded to Internal! Will update here when fixed!
