### ISSUE TITLE
Luxury and Dream ranks do not display on leaderboard

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Bugs-and-Issues#1759]
When pressing tab both Luxury and Dream ranks do not appear. Instead it will display the user as [Ultra] until they reach the rank of master.

Screenies:
![chat](https://user-images.githubusercontent.com/17133410/185763148-f3b8a16e-7529-40b8-81b8-3e07901618eb.png)
![tab](https://user-images.githubusercontent.com/17133410/185763149-ad35cc00-4eec-48e0-aed8-ddb580092fd3.png)

**Comment by HackuJacku** [comment]
Thank you for the report, this was kindly fixed by Val :)
