### ISSUE TITLE
[Pokeloot] Metang and Metagross. 

### ISSUE THREAD

**Issue by EzelBerbier** [NebulaMC-GG/Bugs-and-Issues#1760]
Metang and Metagroos should drop other type of loot instead gold nuggets. If i don't remember wrong they should drop silver and platinum, not sure the quantity. I can't confirm if beldum has the same issue.

![unknown](https://user-images.githubusercontent.com/108286828/185790101-faee75b3-816c-4841-963d-c2a2b2af50cf.png)

**Comment by CenizaRey** [comment]
This has been fixed as per #changelog. Closing.
