### ISSUE TITLE
Meloetta form mod Pirouette

### ISSUE THREAD

**Issue by IRAGEI** [NebulaMC-GG/Bugs-and-Issues#1761]
Moveset Relic song is not a learnable move throught lvl or move tutor, had admin give move to pokemon but error came up on screen not allowing pokemon to transform . Major thanks to MISS ELYRI on Titan , my name is IOneManRageI 
![2022-08-22_00 05 44](https://user-images.githubusercontent.com/111725205/185843917-9c525cb8-db76-45b4-ba15-2aecacd0cbe1.png)

**Comment by Khrisstias** [comment]
Hello! Thanks for the report! https://pixelmonmod.com/tracker.php?p=2&t=19055 this issue has been forwarded to the development team already.
