### ISSUE TITLE
Wrong timed spawning legend

### ISSUE THREAD

**Issue by Blaius** [NebulaMC-GG/Bugs-and-Issues#1762]
Latias spawned at about 2:12am server time, which is still considered night time for a morning spawn. 
![image](https://user-images.githubusercontent.com/107210251/185861268-9079ca8b-c766-48b1-b173-a113683c3e8b.png)

**Comment by CenizaRey** [comment]
You're absolutely sure this occurred at 2:12am according to /time, and not JourneyMap? Because JourneyMap's clock is completely distorted.

**Comment by MissElyri** [comment]
@CenizaRey 110% sure, as I'm the one who did /time, (I know normal players couldn't use it, and not sure about staff under admin) I can check my chat logs later when home and get you those. There were a lot of us on and we were all super confused on why it spawned at night.

**Comment by EzelBerbier** [comment]
On Atlas happened something similar with the Darkrai that spawned on me today. I don't have any proves to share, but spawned when it was sunrise and im totally sure about it, I think I talked about that in chat cause hadn't any sense for me that spawn.

**Comment by fatyg5** [comment]
The Latias issue most likely existed from the fact that it spawned in our spawn area, which has a different time than the regular world. Closing as I will be addressing this issue soon with a fixed file anyway.
