### ISSUE TITLE
Tpa requests not showing

### ISSUE THREAD

**Issue by ParadoxalGlitch** [NebulaMC-GG/Bugs-and-Issues#1763]
When someone sends a tpa request, the player that should receive the request doesn't get the message, but can hear the sound and accept it. For now, I've only seen this issue in 2 players, including me and relogging or restarting the game doesn't fix it.

**Comment by Deathnight7976** [comment]
Server: Atlas

**Comment by KittyKatzyn** [comment]
Seems fixed by this point, so, closing!  :)
