### ISSUE TITLE
Can't send chat messages on Atlas

### ISSUE THREAD

**Issue by Hawkyshadows** [NebulaMC-GG/Bugs-and-Issues#1764]
When logging on this morning I couldn't seem to speak in any type of chat: general, staff, dms nothing seems to be sending I can chat just find on titan and orion but not Atlas I can see dms I'm sent and I send but I can't reply nor can they see my replies, only hear the noise apparently my commands work fine just can't chat

**Comment by HackuJacku** [comment]
Can you screenshot your `esc` -> `Options` -> `Chat Settings...` UI please, @Hawkyshadows?

**Comment by HackuJacku** [comment]
Closing due to no response.
