### ISSUE TITLE
Glows

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Bugs-and-Issues#1766]
Glow syncing issue:
Despite my glow being on only my tag is affected.
Toggling my glow then turns it back on until I relaunch however, it appears other players who remained online since the last time i toggled my glow can still see said glow, despite being off for me.

Glow:
![noglow](https://user-images.githubusercontent.com/17133410/185950727-48198615-2a83-4683-8fb6-cfdeb1bef5c4.png)
![GlowGui](https://user-images.githubusercontent.com/17133410/185950747-7d913fa2-f030-4323-837e-74495b89943d.png)

Nametag:
![glowtag](https://user-images.githubusercontent.com/17133410/185953346-26291833-22b5-4659-aaa0-dbdb1d4a73ea.png)

**Comment by KittyKatzyn** [comment]
Seems this is fixed!  Closing!

**Comment by KittyKatzyn** [comment]
Forwarded! Will be updated here when fixed!

**Comment by chefburne** [comment]
no longer relevant, closing
