### ISSUE TITLE
No Pokeballs showing in shulker to use in Raid Den

### ISSUE THREAD

**Issue by FoxArcher** [NebulaMC-GG/Bugs-and-Issues#1767]
When battling you can use pokeballs that are stored in shulker boxes. But when entering a raid battle after defeating Pokémon shows no balls to be used.
![image](https://user-images.githubusercontent.com/108157492/185955926-6505e505-a1dc-452d-a5ec-f797f201634b.png)
![image](https://user-images.githubusercontent.com/108157492/185956300-cc90a1c6-00fa-436f-8db7-4f7234fa7eec.png)
You can see white shulker in my inv that has balls in prev SS.
![image](https://user-images.githubusercontent.com/108157492/185956544-d746cdc8-4750-4164-81a4-b2f4546cbd92.png)
Even though Pokeballs are present in shulker in INV they are not able to be used.

**Comment by Rasgnarok** [comment]
This is a Pixelmon issue, already been forwarded. Closing.
