### ISSUE TITLE
Bingo card reset with over 9 hours left

### ISSUE THREAD

**Issue by MeokubaMC** [NebulaMC-GG/Bugs-and-Issues#1768]
I went AFK for a short while to take care of issues and was of course eventually disconnected for being AFK for 15 minutes, but when I returned to continue working on my bingo card it was almost completely reset. I'm not sure if this is proof enough or if this is an issue that can be resolved but I thought I'd try anyway.
![image](https://user-images.githubusercontent.com/111777030/185971198-9faaa8e8-0361-44e5-8d66-621e09b72f68.png)
![image](https://user-images.githubusercontent.com/111777030/185971274-af1f084f-1af8-4dc8-9c9a-698c52536b4d.png)
![image](https://user-images.githubusercontent.com/111777030/185971310-ac9e7f67-6a2b-412a-b8d0-dd9bc38186f5.png)

**Comment by HackuJacku** [comment]
This is now fixed, thank you for reporting it.
