### ISSUE TITLE
Omen Weekly failing to give full Rewards

### ISSUE THREAD

**Issue by Chunkkss** [NebulaMC-GG/Bugs-and-Issues#1769]
![2022-08-22_10 30 46](https://user-images.githubusercontent.com/107234416/185972431-290b5e79-c9ac-4ead-bdc6-04bcb47022c0.png)
![2022-08-22_10 31 13](https://user-images.githubusercontent.com/107234416/185972456-f1978bf9-ec11-4479-9753-2bf628715f54.png)

5x Golden Hourglasses
3x Golden Lenses
3x Super Repel
7x XL Exp. Candies 
 not recieved in kit

**Comment by MissElyri** [comment]
Will refund when next online. (Shortly)

**Comment by fatyg5** [comment]
Fixed. Thank you for the report.
