### ISSUE TITLE
Add the storm/rain condition to pokemon that only has one of the two

### ISSUE THREAD

**Issue by Lieren-HuntGhosts** [NebulaMC-GG/Bugs-and-Issues#1770]
Some pokemon like Lotad only spawn during Rain, therefore if storm begins, lotad won't spawn. It would be nice to have pokemon that have that conditions fixed to have both.

All pokemon with that condition I know of are:

-Lotad
-Mudkip

I currently can't think of any other pokemon with them. Will edit if so.

**Comment by CenizaRey** [comment]
Done, thanks for the suggestion! Closing.
