### ISSUE TITLE
Vote Crate Preview Inaccurate

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Bugs-and-Issues#1772]
Vote crate preview displays the ability to win 10x pokeballs however post crate update that number is 16x

Screenies:
![Votecratepreview](https://user-images.githubusercontent.com/17133410/186005822-afa0b572-90d5-44a5-b7e1-a19330dbd0db.png)

![Tx4zCjj](https://user-images.githubusercontent.com/17133410/186006215-87d25cf6-d375-4bdc-9ff2-7aa1ee285904.png)

**Comment by HackuJacku** [comment]
Fixed in upcoming version on beta. Working on adding Nature Modifiers first :))
