### ISSUE TITLE
rank glows not showing up

### ISSUE THREAD

**Issue by Crimlatheloli** [NebulaMC-GG/Bugs-and-Issues#1773]
on the store page it says jade rank gets white, yellow, dark grey, grey, black, aqua, gold, light purple, dark purple and blue player glows but in game I only have white, yellow, dark grey, grey, black, aqua, gold, and blue player glows is this the correct amount and the store is wrong or is the light and dark purple glows not showing up for some reason?

**Comment by Chunkkss** [comment]
Resolved.
