### ISSUE TITLE
ThunderStoneHelmet

### ISSUE THREAD

**Issue by koy0561** [NebulaMC-GG/Bugs-and-Issues#1774]
ThunderStone Helmet wouldnt let me manually drop it into helmet spot, would let me shift click and right click from hotbar but not manually put it onto head
![image](https://user-images.githubusercontent.com/111909101/186233315-dca80e56-9110-43ca-a3ce-4d2fe33ca6ef.png)

**Comment by KittyKatzyn** [comment]
This seems to be fixed; closing!
