### ISSUE TITLE
A little bug with Palette Modifiers

### ISSUE THREAD

**Issue by innqmorato** [NebulaMC-GG/Bugs-and-Issues#1777]
Starting with the fact that i don't know if creator forms are supposed to be included in palette mod, when you try using a them on a cinderace, greninja or sentret it doesn't really work properly, see images below for proof.
![2022-08-24_03 06 27](https://user-images.githubusercontent.com/109287888/186295481-fef4dfa6-e6b4-4d53-876e-c07cb65ca330.png)
![2022-08-24_03 06 32](https://user-images.githubusercontent.com/109287888/186295483-7d04ed12-e8dc-419b-872e-42bf4ba8da43.png)
![2022-08-24_03 06 46](https://user-images.githubusercontent.com/109287888/186295486-1f1e0299-6867-4302-a3e5-29c8fa180b99.png)

**Comment by HackuJacku** [comment]
Thank you for reporting this bug, it will be fixed when the server is rebooted :)
