### ISSUE TITLE
Master Create not giving all items

### ISSUE THREAD

**Issue by Th3Boog** [NebulaMC-GG/Bugs-and-Issues#1778]
i just got my master crates and i didn't get my ability mod and my iv mod thats about it

**Comment by fatyg5** [comment]
I do not see a reason why this would have failed to give it to you, but could I get your IGN and the server you play on so I can refund?

**Comment by MissElyri** [comment]
@fatyg5 this player has been refunded. Th3_Boog on Titan;.

**Comment by HackuJacku** [comment]
Closing as the player has been refunded.
