### ISSUE TITLE
Ultimate Boss Pool Loot - Orion

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Bugs-and-Issues#1780]
After killing an Ultimate boss on Orion I received an Air.

Screenies:
![Air](https://user-images.githubusercontent.com/17133410/186551197-8ba29829-90ed-407e-a161-d48faf5c5c3c.png)

Server: Orion
IGN: Deathnight7976

**Comment by KittyKatzyn** [comment]
This should be fixed with the next datapack update!  Closing!
